// api/info.js - Vercel Serverless Function Replacement for Server.java
module.exports = function handler(req, res) {
    // Add CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Content-Type', 'application/json; charset=UTF-8');

    const { topic = '1', lang = 'en' } = req.query;

    const db = {
        "1": {
            "en": { "title": "About College", "text": "Jain College of Engineering and Research, Belgaum, Karnataka has rapidly emerged as a premier institution since its establishment in 2010, offering world-class engineering and management education. This dynamic institution is renowned for its commitment to academic excellence, innovative teaching methods, and industry-driven curriculum, making it the perfect choice for students and parents alike. With strong affiliations to VTU Belagavi and AICTE accreditation.", "imageUrl": null },
            "hi": { "title": "कॉलेज के बारे में", "text": "जैन कॉलेज ऑफ इंजीनियरिंग एंड रिसर्च, बेलगाम, कर्नाटक 2010 में अपनी स्थापना के बाद से एक प्रमुख संस्थान के रूप में तेजी से उभरा है, जो विश्व स्तरीय इंजीनियरिंग और प्रबंधन शिक्षा प्रदान करता है। वीटीयू बेलगावी और एआईसीटीई मान्यता के साथ, कॉलेज गुणवत्तापूर्ण शिक्षा और प्रगति का प्रतीक है।", "imageUrl": null },
            "kn": { "title": "ಕಾಲೇಜಿನ ಬಗ್ಗೆ", "text": "ಜೈನ್ ಕಾಲೇಜ್ ಆಫ್ ಇಂಜಿನಿಯರಿಂಗ್ ಅಂಡ್ ರಿಸರ್ಚ್, ಬೆಳಗಾವಿ, ಕರ್ನಾಟಕವು 2010 ರಲ್ಲಿ ಸ್ಥಾಪನೆಯಾದಂದಿನಿಂದ ವಿಶ್ವದರ್ಜೆಯ ಇಂಜಿನಿಯರಿಂಗ್ ಶಿಕ್ಷಣವನ್ನು ನೀಡುವ ಪ್ರಮುಖ ಸಂಸ್ಥೆಯಾಗಿ ಹೊರಹೊಮ್ಮಿದೆ. ವಿಟಿಯು ಬೆಳಗಾವಿ ಮತ್ತು ಎಐಸಿಟಿಇ ಮಾನ್ಯತೆಯೊಂದಿಗೆ, ಕಾಲೇಜು ಗುಣಮಟ್ಟದ ಶಿಕ್ಷಣದ ಸಂಕೇತವಾಗಿ ನಿಂತಿದೆ.", "imageUrl": null }
        },
        "1_principal": {
            "en": { "title": "Principal Sir", "text": "DOCTOR S. V. Gorabal sir is the Principal of Jain College of Engineering and Research, Belgaum. He is a visionary leader with extensive experience in technical education and research. Under his guidance, the institution has achieved significant milestones in academic excellence and student development.", "imageUrl": "images/principale.jpg.png", "spokenText": "Doctor S. V. Gorabal sir is the Principal of Jain College of Engineering and Research, Belgaum. He is a visionary leader with extensive experience in technical education and research. Under his guidance, the institution has achieved significant milestones in academic excellence and student development." },
            "hi": { "title": "प्राचार्य महोदय", "text": "डॉ. एस. वी. गोरबल सर जैन कॉलेज ऑफ इंजीनियरिंग एंड रिसर्च, बेलगाम के प्राचार्य हैं। वह एक दूरदर्शी नेता हैं जिन्हें तकनीकी शिक्षा और अनुसंधान का व्यापक अनुभव है। उनके मार्गदर्शन में, संस्थान ने अकादमिक उत्कृष्टता और छात्र विकास में महत्वपूर्ण मील के पत्थर हासिल किए हैं।", "imageUrl": "images/principale.jpg.png" },
            "kn": { "title": "ಪ್ರಾಂಶುಪಾಲರು", "text": "ಡಾ. ಎಸ್. ವಿ. ಗೊರಬಾಳ್ ಸರ್ ಅವರು ಬೆಳಗಾವಿಯ ಜೈನ್ ಕಾಲೇಜ್ ಆಫ್ ಇಂಜಿನಿಯರಿಂಗ್ ಅಂಡ್ ರಿಸರ್ಚ್‌ನ ಪ್ರಾಂಶುಪಾಲರಾಗಿದ್ದಾರೆ. ಅವರು ತಾಂತ್ರಿಕ ಶಿಕ್ಷಣ ಮತ್ತು ಸಂಶೋಧನೆಯಲ್ಲಿ ಅಪಾರ ಅನುಭವ ಹೊಂದಿರುವ ದಾರ್ಶನಿಕ ನಾಯಕರಾಗಿದ್ದಾರೆ. ಅವರ ಮಾರ್ಗದರ್ಶನದಲ್ಲಿ, ಸಂಸ್ಥೆಯು ಶೈಕ್ಷಣಿಕ ವಿಭಾಗ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳ ಅಭಿವೃದ್ಧಿಯಲ್ಲಿ ಗಮನಾರ್ಹ ಸಾಧನೆ ಮಾಡಿದೆ.", "imageUrl": "images/principale.jpg.png" }
        },
        "1_faculty": {
            "en": { "title": "College Faculty", "text": "JCER boasts a team of highly qualified and dedicated faculty members across all departments. Our educators are committed to student success, research, and holistic development. They bring both industrial and academic expertise to the classroom.", "imageUrl": "images/college_faculty.jpg" },
            "hi": { "title": "कॉलेज फैकल्टी", "text": "जेसीईआर के सभी विभागों में उच्च योग्य और समर्पित फैकल्टी सदस्यों की एक टीम है। हमारे शिक्षक छात्रों की सफलता और शोध के लिए प्रतिबद्ध हैं।", "imageUrl": "images/college_faculty.jpg" },
            "kn": { "title": "ಕಾಲೇಜು ಬೋಧಕ ವರ್ಗ", "text": "ಜೆಸಿಇಆರ್ ಎಲ್ಲಾ ವಿಭಾಗಗಳಲ್ಲಿ ಉನ್ನತ ಗುಣಮಟ್ಟದ ಬೋಧಕರ ತಂಡವನ್ನು ಹೊಂದಿದೆ. ಅವರು ವಿದ್ಯಾರ್ಥಿಗಳ ಅಭಿವೃದ್ಧಿಗೆ ಮತ್ತು ಸಂಶೋಧನೆಗೆ ಶ್ರಮಿಸುತ್ತಿದ್ದಾರೆ.", "imageUrl": "images/college_faculty.jpg" }
        },
        "2": {
            "en": { "title": "Admission Process", "text": "Welcome to Jain College of Engineering and Research. We offer Undergraduate and Postgraduate courses in various streams. Admission can be taken through UGCET, DCET, or Management quota. \n\nWe provide courses in:\n• <u>Computer Science & Engineering</u>\n• <u>Electronics & Communication Engineering</u>\n• <u>Artificial Intelligence & Machine Learning</u>\n• <u>Mechanical Engineering</u>\n• <u>Civil Engineering</u>\n• <u>MBA</u>\n\nFor further information, please visit office room number G04 and meet Shivakumar Biradar sir. Thank you.", "imageUrl": null },
            "hi": { "title": "प्रवेश प्रक्रिया", "text": "जैन कॉलेज ऑफ इंजीनियरिंग एंड रिसर्च में आपका स्वागत है। हम विभिन्न इंजीनियरिंग धाराओं में स्नातक पाठ्यक्रम प्रदान करते हैं। प्रवेश UGCET, DCET या प्रबंधन कोटे के माध्यम से लिया जा सकता है।\n\nहम निम्नलिखित पाठ्यक्रम प्रदान करते हैं:\n• <u>कंप्यूटर साइंस एंड इंजीनियरिंग</u>\n• <u>इलेक्ट्रॉनिक्स एंड कम्युनिकेशन इंजीनियरिंग</u>\n• <u>आर्टिफिशियल इंटेलिजेंस और मशीन लर्निंग</u>\n• <u>मैकेनिकल इंजीनियरिंग</u>\n• <u>सिविल इंजीनियरिंग</u>\n• <u>एमबीए</u>\n\nअधिक जानकारी के लिए, कृपया कार्यालय कक्ष संख्या G04 में जाएँ और शिवकुमार बिरादर सर से मिलें। धन्यवाद।", "imageUrl": null },
            "kn": { "title": "ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆ", "text": "ಜೈನ್ ಕಾಲೇಜ್ ಆಫ್ ಇಂಜಿನಿಯರಿಂಗ್ ಅಂಡ್ ರಿಸರ್ಚ್‌ಗೆ ಸುಸ್ವಾಗತ. ನಾವು ವಿವಿಧ ಇಂಜಿನಿಯರಿಂಗ್ ವಿಭಾಗಗಳಲ್ಲಿ ಪದವಿ ಕೋರ್ಸ್‌ಗಳನ್ನು ನೀಡುತ್ತೇವೆ. UGCET, DCET ಅಥವಾ ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಕೋಟಾದ ಮೂಲಕ ಪ್ರವೇಶ ಪಡೆಯಬಹುದು.\n\nನಾವು ಈ ಕೆಳಗಿನ ಕೋರ್ಸ್‌ಗಳನ್ನು ನೀಡುತ್ತೇವೆ:\n• <u><b>ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಅಂಡ್ ಇಂಜಿನಿಯರಿಂಗ್</b></u>\n• <u><b>ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಅಂಡ್ ಕಮ್ಯುನಿಕೇಷನ್ ಇಂಜಿನಿಯರಿಂಗ್</b></u>\n• <u><b>ಆರ್ಟಿಫಿಶಿಯಲ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಮತ್ತು ಮಷಿನ್ ಲರ್ನಿಂಗ್</b></u>\n• <u><b>ಮೆಕ್ಯಾನಿಕಲ್ ಇಂಜಿನಿಯರಿಂಗ್</b></u>\n• <u><b>ಸಿವಿಲ್ ಇಂಜಿನಿಯರಿಂಗ್</b></u>\n• <u><b>ಎಂಬಿಎ</b></u>\n\nಹೆಚ್ಚಿನ ಮಾಹಿತಿಗಾಗಿ, ದಯವಿಟ್ಟು ಕಚೇರಿ ಕೊಠಡಿ ಸಂಖ್ಯೆ G04 ಗೆ ಭೇಟಿ ನೀಡಿ ಮತ್ತು ಶಿವಕುಮಾರ್ ಬಿರಾದಾರ್ ಸರ್ ಅವರನ್ನು ಭೇಟಿ ಮಾಡಿ. ಧನ್ಯವಾದಗಳು.", "imageUrl": null }
        },
        "2_ugcet": {
            "en": { "title": "UGCET Admission", "text": "UGCET (KCET) admission is for students seeking entry into the first year of engineering. Candidates must participate in the KEA counseling process based on their CET rank. JCER generally follows the Karnataka government-mandated fee structure for CET (KCET) students, which is approximately ₹90,000 to ₹1 Lakh per year (around ₹3.6 Lakhs - ₹4 Lakhs for 4 years) for tuition, excluding additional college/exam fees. The KCET code for JCER is E269.", "imageUrl": null },
            "hi": { "title": "UGCET प्रवेश", "text": "UGCET (KCET) प्रवेश उन छात्रों के लिए है जो इंजीनियरिंग के प्रथम वर्ष में प्रवेश लेना चाहते हैं। उम्मीदवारों को अपनी CET रैंक के आधार पर KEA काउंसलिंग प्रक्रिया में भाग लेना होगा। जेसीईआर (JCER) आमतौर पर CET (KCET) छात्रों के लिए कर्नाटक सरकार द्वारा अनिवार्य शुल्क संरचना का पालन करता है, जो शिक्षण शुल्क के लिए लगभग ₹90,000 से ₹1 लाख प्रति वर्ष (4 वर्षों के लिए लगभग ₹3.6 लाख - ₹4 लाख) है, जिसमें अतिरिक्त कॉलेज/परीक्षा शुल्क शामिल नहीं है। जेसीईआर का KCET कोड E269 है।", "imageUrl": null },
            "kn": { "title": "UGCET ಪ್ರವೇಶ", "text": "UGCET (KCET) ಪ್ರವೇಶವು ಇಂಜಿನಿಯರಿಂಗ್‌ನ ಮೊದಲ ವರ್ಷಕ್ಕೆ ಪ್ರವೇಶ ಪಡೆಯಲು ಇಚ್ಛಿಸುವ ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ. ಅಭ್ಯರ್ಥಿಗಳು ತಮ್ಮ CET ರ್‍ಯಾಂಕ್‌ನ ಆಧಾರದ ಮೇಲೆ KEA ಕೌನ್ಸೆಲಿಂಗ್ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ಭಾಗವಹಿಸಬೇಕು. JCER ಸಾಮಾನ್ಯವಾಗಿ CET (KCET) ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಕರ್ನಾಟಕ ಸರ್ಕಾರವು ನಿಗದಿಪಡಿಸಿದ ಶುಲ್ಕ ರಚನೆಯನ್ನು ಅನುಸರಿಸುತ್ತದೆ, ಇದು ಬೋಧನೆಗಾಗಿ (tuition) ವರ್ಷಕ್ಕೆ ಸರಿಸುಮಾರು ₹90,000 ದಿಂದ ₹1 ಲಕ್ಷದವರೆಗೆ ಇರುತ್ತದೆ (4 ವರ್ಷಗಳಿಗೆ ಸುಮಾರು ₹3.6 ಲಕ್ಷದಿಂದ ₹4 ಲಕ್ಷ), ಹೆಚ್ಚುವರಿ ಕಾಲೇಜು/ಪರೀಕ್ಷಾ ಶುಲ್ಕಗಳನ್ನು ಹೊರತುಪಡಿಸಿ. JCER ನ KCET ಕೋಡ್ E269 ಆಗಿದೆ.", "imageUrl": null }
        },
        "2_dcet": {
            "en": { "title": "DCET Admission", "text": "DCET admission is for Diploma students seeking lateral entry into the second year (3rd semester) of engineering. Candidates must clear the Diploma CET and participate in counseling. The total fee for the BE {Lateral} course at JCER is approximately ₹3.67 Lakhs to ₹6 Lakhs for the entire duration.", "imageUrl": null },
            "hi": { "title": "DCET प्रवेश", "text": "DCET प्रवेश उन डिप्लोमा छात्रों के लिए है जो इंजीनियरिंग के द्वितीय वर्ष (तीसरे सेमेस्टर) में लेटरल एंट्री के माध्यम से प्रवेश लेना चाहते हैं। उम्मीदवारों को डिप्लोमा CET उत्तीर्ण करना होगा और काउंसलिंग में भाग लेना होगा। JCER में BE (लेटरल) कोर्स के लिए कुल शुल्क पूरी अवधि के लिए लगभग ₹3.67 लाख से ₹6 लाख तक है।", "imageUrl": null },
            "kn": { "title": "DCET ಪ್ರವೇಶ", "text": "DCET ಪ್ರವೇಶವು ಇಂಜಿನಿಯರಿಂಗ್‌ನ ಎರಡನೇ ವರ್ಷಕ್ಕೆ (3ನೇ ಸೆಮಿಸ್ಟರ್) ಲ್ಯಾಟರಲ್ ಎಂಟ್ರಿ ಮೂಲಕ ಪ್ರವೇಶ ಪಡೆಯಲು ಇಚ್ಛಿಸುವ ಡಿಪ್ಲೊಮಾ ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ. ಅಭ್ಯರ್ಥಿಗಳು ಡಿಪ್ಲೊಮಾ CET ಯನ್ನು ತೇರ್ಗಡೆ ಹೊಂದಬೇಕು ಮತ್ತು ಕೌನ್ಸೆಲಿಂಗ್‌ನಲ್ಲಿ ಭಾಗವಹಿಸಬೇಕು. JCER ನಲ್ಲಿ BE (ಲ್ಯಾಟರಲ್) ಕೋರ್ಸ್‌ಗೆ ಒಟ್ಟು ಶುಲ್ಕವು ಸಂಪೂರ್ಣ ಅವಧಿಗೆ ಅಂದಾಜು ₹3.67 ಲಕ್ಷದಿಂದ ₹6 ಲಕ್ಷದವರೆಗೆ ಇರುತ್ತದೆ.", "imageUrl": null }
        },
        "2_management": {
            "en": { "title": "Management Admission", "text": "For direct admission under Management Quota, please visit the college office at room G04 and meet Shivakumar Biradar sir. You can also contact us at principal@jcer.in for fee details.", "imageUrl": null },
            "hi": { "title": "मैनेजमेंट प्रवेश", "text": "मैनेजमेंट कोटे के तहत सीधे प्रवेश के लिए, कृपया कॉलेज कार्यालय के कमरा G04 में जाएं और शिवकुमार बिरादर सर से मिलें। आप शुल्क विवरण के लिए हमसे principal@jcer.in पर संपर्क भी कर सकते हैं।", "imageUrl": null },
            "kn": { "title": "ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಪ್ರವೇಶ", "text": "ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಕೋಟಾದ ಅಡಿಯಲ್ಲಿ ನೇರ ಪ್ರವೇಶಕ್ಕಾಗಿ, ದಯವಿಟ್ಟು ಕಾಲೇಜು ಕಚೇರಿಯ ಕೊಠಡಿ G04 ಗೆ ಭೇಟಿ ನೀಡಿ ಮತ್ತು ಶಿವಕುಮಾರ್ ಬಿರಾದಾರ್ ಸರ್ ಅವರನ್ನು ಭೇಟಿ ಮಾಡಿ. ಶುಲ್ಕದ ವಿವರಗಳಿಗಾಗಿ ನೀವು ನಮ್ಮನ್ನು principal@jcer.in ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಬಹುದು.", "imageUrl": null }
        },
        "2_faculty": {
            "en": { "title": "Admission Team", "text": "For admission related queries, please contact our dedicated admission cell led by Shivakumar Biradar sir.", "imageUrl": "images/faculty_admission.jpg" },
            "hi": { "title": "प्रवेश टीम", "text": "प्रवेश संबंधी पूछताछ के लिए, कृपया शिवकुमार बिरादर सर के नेतृत्व वाली हमारी समर्पित प्रवेश टीम से संपर्क करें।", "imageUrl": "images/faculty_admission.jpg" },
            "kn": { "title": "ಪ್ರವೇಶ ತಂಡ", "text": "ಪ್ರವೇಶಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ವಿಚಾರಣೆಗಾಗಿ, ದಯವಿಟ್ಟು ಶಿವಕುಮಾರ್ ಬಿರಾದಾರ್ ಸರ್ ನೇತೃತ್ವದ ನಮ್ಮ ಪ್ರವೇಶ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ.", "imageUrl": "images/faculty_admission.jpg" }
        },
        "3": {
            "en": { "title": "Computer Science & Engineering", "text": "The Department of Computer Science & Engineering was established in 2018 with an intake of 120, and a dedicated Research Center was established in 2024. We are committed to continuously improving the quality of education with highly qualified staff and centralized laboratories featuring the latest software tools. Our four-year undergraduate program provides a solid foundation in CSE principles and emerging technologies, equipping students to solve complex problems and succeed in the IT industry.", "imageUrl": "images/cse_dept.jpg.jpeg" },
            "hi": { "title": "कंप्यूटर साइंस एंड इंजीनियरिंग", "text": "कंप्यूटर विज्ञान और इंजीनियरिंग विभाग 2018 में 120 की प्रवेश क्षमता के साथ स्थापित किया गया था, और 2024 में एक समर्पित अनुसंधान केंद्र स्थापित किया गया था। हम उच्च योग्य संकाय और नवीनतम सॉफ्टवेयर उपकरणों वाली केंद्रीकृत प्रयोगशालाओं के साथ शिक्षा की गुणवत्ता में निरंतर सुधार के लिए प्रतिबद्ध हैं। हमारा चार साल का स्नातक कार्यक्रम सीएसई सिद्धांतों और उभरती प्रौद्योगिकियों में एक ठोस आधार प्रदान करता है।", "imageUrl": "images/cse_dept.jpg.jpeg" },
            "kn": { "title": "ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಅಂಡ್ ಇಂಜಿನಿಯರಿಂಗ್", "text": "ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಮತ್ತು ಇಂಜಿನಿಯರಿಂಗ್ ವಿಭಾಗವನ್ನು 2018 ರಲ್ಲಿ 120 ರ ಮೊತ್ತದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಯಿತು ಮತ್ತು 2024 ರಲ್ಲಿ ಸಂಶೋಧನಾ ಕೇಂದ್ರವನ್ನು ಸ್ಥಾಪಿಸಲಾಯಿತು. ನಾವು ಉನ್ನತ ಗುಣಮಟ್ಟದ ಬೋಧಕರ ತಂಡ ಮತ್ತು ಇತ್ತೀಚಿನ ಸಾಫ್ಟ್‌ವೇರ್ ಪರಿಕರಗಳೊಂದಿಗೆ ಗುಣಮಟ್ಟದ ಶಿಕ್ಷಣವನ್ನು ನೀಡಲು ಬದ್ಧರಾಗಿದ್ದೇವೆ. ನಮ್ಮ ನಾಲ್ಕು ವರ್ಷಗಳ ಪದವಿ ಕಾರ್ಯಕ್ರಮವು ಸಿಎಸ್‌ಇ ತತ್ವಗಳು ಮತ್ತು ಉದಯೋನ್ಮುಖ ತಂತ್ರಜ್ಞಾನಗಳಲ್ಲಿ ಭದ್ರ ಬುನಾದಿಯನ್ನು ಒದಗಿಸುತ್ತದೆ.", "imageUrl": "images/cse_dept.jpg.jpeg" }
        },
        "3_faculty": {
            "en": { "title": "CSE Faculty Members", "text": "The CSE department features a distinguished team of experts: \n\n1. Doctor Pritam Dhumale (HOD, Professor)\n2. Doctor Jyothi B R (Associate Professor & Dean NAAC)\n3. Doctor Pradnya Malaganve (Associate Professor)\n4. Doctor Raghavendra Katagall (Associate Professor)\n5. Professor Veena B. Mindolli (Assistant Professor)\n6. Professor Bharateesh N. Fadanis (Placement Officer)\n7. Professor Vijayalaxmi S Naganur (Assistant Professor)\n8. Professor Arati Patil (Assistant Professor)\n9. Professor Priyanka Desurkar (Assistant Professor)\n10. Professor Megha V. Patil (Assistant Professor)\n11. Professor Abhilasha J (Assistant Professor)\n12. Professor Vinaya Sarmalkar (Assistant Professor)\n13. Professor Sukhada Inamdar (Assistant Professor)\n14. Professor Suraj R Joshi (Assistant Professor)\n15. Professor Manorma H Patil (Assistant Professor)\n16. Professor Kavya Hullur (Assistant Professor)\n17. Professor Ruthika T Kamble (Assistant Professor)\n18. Professor Rutika Mangaonkar (Assistant Professor)\n19. Professor Swarupa Dhamune (Assistant Professor)\n20. Professor Kusum K Kanbarkar (Assistant Professor)", "imageUrl": "images/cse_dept.jpg.jpeg", "spokenText": "The faculty members are: Doctor Pritam Dhumale, Doctor Jyothi B R, Doctor Pradnya Malaganve, Doctor Raghavendra Katagall, Professor Veena B. Mindolli, Professor Bharateesh N. Fadanis, Professor Vijayalaxmi S Naganur, Professor Arati Patil, Professor Priyanka Desurkar, Professor Megha V. Patil, Professor Abhilasha J, Professor Vinaya Sarmalkar, Professor Sukhada Inamdar, Professor Suraj R Joshi, Professor Manorma H Patil, Professor Kavya Hullur, Professor Ruthika T Kamble, Professor Rutika Mangaonkar, Professor Swarupa Dhamune, and Professor Kusum K Kanbarkar." },
            "hi": { "title": "सीएसई संकाय सदस्य", "text": "सीएसई विभाग के विशेषज्ञ सदस्य:\n\n1. डॉ. प्रीतम धुमाले (एचओडी, प्रोफेसर)\n2. डॉ. ज्योति बी आर (एसोसिएट प्रोफेसर व डीन NAAC)\n3. डॉ. प्रज्ञा मालगांवे (एसोसिएट प्रोफेसर)\n4. डॉ. राघवेंद्र कटगाल (एसोसिएट प्रोफेसर)\n5. प्रो. वीणा बी. मिंडोली (असिस्टेंट प्रोफेसर)\n6. प्रो. भरतीश एन. फडनीस (प्लेसमेंट ऑफिसर)\n7. प्रो. विजयलक्ष्मी एस नागनूर (असिस्टेंट प्रोफेसर)\n8. प्रो. आरती पाटिल (असिस्टेंट प्रोफेसर)\n9. प्रो. प्रियंका देसुरकर (असिस्टेंट प्रोफेसर)\n10. प्रो. मेघा वी. पाटिल (असिस्टेंट प्रोफेसर)\n11. प्रो. अभिलाषा जे (असिस्टेंट प्रोफेसर)\n12. प्रो. विनया सरमलकर (असिस्टेंट प्रोफेसर)\n13. प्रो. सुखदा इनामदार (असिस्टेंट प्रोफेसर)\n14. प्रो. सूरज आर जोशी (असिस्टेंट प्रोफेसर)\n15. प्रो. मनोरमा एच पाटिल (असिस्टेंट प्रोफेसर)\n16. प्रो. काव्या हुल्लूर (असिस्टेंट प्रोफेसर)\n17. प्रो. ऋतिका टी कांबले (असिस्टेंट प्रोफेसर)\n18. प्रो. ऋतिका मनगांवकर (असिस्टेंट प्रोफेसर)\n19. प्रो. स्वरूपा ढमुने (असिस्टेंट प्रोफेसर)\n20. प्रो. कुसुम के कनबरकर (असिस्टेंट प्रोफेसर)", "imageUrl": "images/cse_dept.jpg.jpeg", "spokenText": "संकाय सदस्यों में: डॉ. प्रीतम धुमाले, डॉ. ज्योति बी आर, डॉ. प्रज्ञा मालगांवे, डॉ. राघवेंद्र कटगाल, प्रो. वीणा बी. मिंडोली, प्रो. भरतीश एन. फडनीस, प्रो. विजयलक्ष्मी एस नागनूर, प्रो. आरती पाटिल, प्रो. प्रियंका देसुरकर, प्रो. मेघा वी. पाटिल, प्रो. अभिलाषा जे, प्रो. विनया सरमलकर, प्रो. सुखदा इनामदार, प्रो. सूरज आर जोशी, प्रो. मनोरमा एच पाटिल, प्रो. काव्या हुल्लूर, प्रो. ऋतिका टी कांबले, प्रो. ऋतिका मनगांवकर, प्रो. स्वरूपा ढमुने, और प्रो. कुसुम के कनबरकर शामिल हैं।" },
            "kn": { "title": "ಸಿಎಸ್ಇ ಬೋಧಕ ವರ್ಗ", "text": "ಸಿಎಸ್‌ಇ ವಿಭಾಗದ ತಜ್ಞ ಸದಸ್ಯರು:\n\n1. ಡಾ. ಪ್ರೀತಮ್ ಧುಮಾಳೆ (ಎಚ್‌ಒಡಿ, ಪ್ರೊಫೆಸರ್)\n2. ಡಾ. ಜ್ಯೋತಿ ಬಿ ಆರ್ (ಅಸೋಸಿಯೇಟ್ ಪ್ರೊಫೆಸರ್ ಮತ್ತು ಡೀನ್ NAAC)\n3. ಡಾ. ಪ್ರಜ್ಞಾ ಮಲಗಾನ್ವೆ (ಅಸೋಸಿಯೇಟ್ ಪ್ರೊಫೆಸರ್)\n4. ಡಾ. ರಾಘವೇಂದ್ರ ಕಟಗಾಲ್ (ಅಸೋಸಿಯೇಟ್ ಪ್ರೊಫೆಸರ್)\n5. ಪ್ರೊ. ವೀಣಾ ಬಿ. ಮಿಂದೋಳಿ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n6. ಪ್ರೊ. ಭರತೀಶ್ ಎನ್. ಫಡ್ನಿಸ್ (ಪ್ಲೇಸ್‌ಮೆಂಟ್ ಆಫೀಸರ್)\n7. ಪ್ರೊ. ವಿಜಯಲಕ್ಷ್ಮಿ ಎಸ್ ನಾಗನೂರು (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n8. ಪ್ರೊ. ಆರತಿ ಪಾಟೀಲ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n9. ಪ್ರೊ. ಪ್ರಿಯಾಂಕಾ ದೇಸೂರ್ಕರ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n10. ಪ್ರೊ. ಮೇಘಾ ವಿ. ಪಾಟೀಲ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n11. ಪ್ರೊ. ಅಭಿಲಾಷಾ ಜೆ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n12. ಪ್ರೊ. ವಿನಯಾ ಸರ್ಮಲ್ಕರ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n13. ಪ್ರೊ. ಸುಖದಾ ಇನಾಂದಾರ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n14. ಪ್ರೊ. ಸೂರಜ್ ಆರ್ ಜೋಶಿ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n15. ಪ್ರೊ. ಮನೋರಮಾ ಹೆಚ್ ಪಾಟೀಲ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n16. ಪ್ರೊ. ಕಾವ್ಯ ಹುಲ್ಲೂರ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n17. ಪ್ರೊ. ರುತಿಕಾ ಟಿ ಕಾಂಬಳೆ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n18. ಪ್ರೊ. ರುತಿಕಾ ಮನಗಾಂವಕರ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n19. ಪ್ರೊ. ಸ್ವರೂಪಾ ಧಮುನೆ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)\n20. ಪ್ರೊ. ಕುಸುಮ್ ಕೆ ಕಣಬರಕರ್ (ಅಸಿಸ್ಟೆಂಟ್ ಪ್ರೊಫೆಸರ್)", "imageUrl": "images/cse_dept.jpg.jpeg", "spokenText": "ಬೋಧಕ ವರ್ಗವು ಡಾ. ಪ್ರೀತಮ್ ಧುಮಾಳೆ, ಡಾ. ಜ್ಯೋತಿ ಬಿ ಆರ್, ಡಾ. ಪ್ರಜ್ಞಾ ಮಲಗಾನ್ವೆ, ಡಾ. ರಾಘವೇಂದ್ರ ಕಟಗಾಲ್, ಪ್ರೊ. ವೀಣಾ ಬಿ. ಮಿಂದೋಳಿ, ಪ್ರೊ. ಭರತೀಶ್ ಎನ್. ಫಡ್ನಿಸ್, ಪ್ರೊ. ವಿಜಯಲಕ್ಷ್ಮಿ ಎಸ್ ನಾಗನೂರು, ಪ್ರೊ. ಆರತಿ ಪಾಟೀಲ್, ಪ್ರೊ. ಪ್ರಿಯಾಂಕಾ ದೇಸೂರ್ಕರ್, ಪ್ರೊ. ಮೇಘಾ ವಿ. ಪಾಟೀಲ್, ಪ್ರೊ. ಅಭಿಲಾಷಾ ಜೆ, ಪ್ರೊ. ವಿನಯಾ ಸರ್ಮಲ್ಕರ್, ಪ್ರೊ. ಸುಖದಾ ಇನಾಂದಾರ್, ಪ್ರೊ. ಸೂರಜ್ ಆರ್ ಜೋಶಿ, ಪ್ರೊ. ಮನೋರಮಾ ಹೆಚ್ ಪಾಟೀಲ್, ಪ್ರೊ. ಕಾವ್ಯ ಹುಲ್ಲೂರ್, ಪ್ರೊ. ರುತಿಕಾ ಟಿ ಕಾಂಬಳೆ, ಪ್ರೊ. ರುತಿಕಾ ಮನಗಾಂವಕರ್, ಪ್ರೊ. ಸ್ವರೂಪಾ ಧಮುನೆ, ಮತ್ತು ಪ್ರೊ. ಕುಸುಮ್ ಕೆ ಕಣಬರಕರ್ ಅವರನ್ನು ಒಳಗೊಂಡಿದೆ." }
        },
        "4": {
            "en": { "title": "Electronics & Communication", "text": "The Department of Electronics & Communication Engineering was established in 2018 with an intake of 60, which increased to 90 in 2023. A dedicated Research Center was established in 2024. The department is committed to imparting quality education and fostering innovation in electronics and communication technologies, preparing students for dynamic careers in academia, industry, and research.", "imageUrl": "images/ece_dpt.jpg.jpeg" },
            "hi": { "title": "इलेक्ट्रॉनिक्स एंड कम्युनिकेशन", "text": "इलेक्ट्रॉनिक्स और संचार इंजीनियरिंग विभाग 2018 में स्थापित किया गया था। यह विभाग गुणवत्तापूर्ण शिक्षा और नवाचार के लिए समर्पित है, जो छात्रों को आधुनिक तकनीकों, अनुसंधान और उद्योग की चुनौतियों के लिए तैयार करता है। 2024 में यहां एक शोध केंद्र भी शुरू किया गया है।", "imageUrl": "images/ece_dpt.jpg.jpeg" },
            "kn": { "title": "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಅಂಡ್ ಕಮ್ಯುನಿಕೇಷನ್", "text": "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಕಮ್ಯುನಿಕೇಷನ್ ಇಂಜಿನಿಯರಿಂಗ್ ವಿಭಾಗವನ್ನು 2018 ರಲ್ಲಿ ಸ್ಥಾಪಿಸಲಾಯಿತು. ವಿಭಾಗವು ಗುಣಮಟ್ಟದ ಶಿಕ್ಷಣ ಮತ್ತು ನಾವೀನ್ಯತೆಗೆ ಸಮರ್ಪಿತವಾಗಿದೆ, ಇದು ಆಧುನಿಕ ತಂತ್ರಜ್ಞಾನಗಳು, ಸಂಶೋಧನೆ ಮತ್ತು ಉದ್ಯಮದ ಸವಾಲುಗಳಿಗೆ ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತದೆ.", "imageUrl": "images/ece_dpt.jpg.jpeg" }
        },
        "4_faculty": {
            "en": { "title": "ECE Faculty Members", "text": "The ECE department features a distinguished team of experts: \n\n1. Professor Chaitanya K. Jambotkar (HOD)\n2. Doctor Virupaxi B. Dalal\n3. Doctor Raghavendra R. Maggavi\n4. Doctor Veeresh M. Hiremath\n5. Doctor Soumya Halagatti\n6. Professor Govinda M R\n7. Professor Vivek Kajagar\n8. Professor Narayana Reddy D\n9. Professor Vijaykumar Patil\n10. Professor Ashwini L. Gudyalakar\n11. Professor Supriya N. Kadrolkar\n12. Professor Rajani V Adikarnataka\n13. Professor Jayashree More\n14. Professor Sneha A. Jagajampi", "imageUrl": "images/ece_dpt.jpg.jpeg", "spokenText": "The faculty members are: Professor Chaitanya K. Jambotkar, Doctor Virupaxi B. Dalal, Doctor Raghavendra R. Maggavi, Doctor Veeresh M. Hiremath, Doctor Soumya Halagatti, Professor Govinda M R, Professor Vivek Kajagar, Professor Narayana Reddy D, Professor Vijaykumar Patil, Professor Ashwini L. Gudyalakar, Professor Supriya N. Kadrolkar, Professor Rajani V Adikarnataka, Professor Jayashree More, and Professor Sneha A. Jagajampi." },
            "hi": { "title": "ईसीई संकाय सदस्य", "text": "ईसीई विभाग के विशेषज्ञ सदस्य:\n\n1. प्रो. चैतन्य के. जंबोटकर (एचओडी)\n2. डॉ. विरूपाक्षी बी. दलाल\n3. डॉ. राघवेंद्र आर. मग्गवी\n4. डॉ. वीरेश एम. हिरेमठ\n5. डॉ. सौम्या हलगट्टी\n6. प्रो. गोविंदा एम आर\n7. प्रो. विवेक काजगर\n8. प्रो. नारायण रेड्ಡಿ डी\n9. प्रो. विजयकुमार पाटिल\n10. प्रो. अश्विनी एल. गुडलकर\n11. प्रो. सुप्रिया एन. काद्रोलकर\n12. प्रो. रजनी वी आदिकर्नाटक\n13. प्रो. जयश्री मोरे\n14. प्रो. स्नेहा ए. जगजंपी", "imageUrl": "images/ece_dpt.jpg.jpeg" },
            "kn": { "title": "ಇಸಿಇ ಬೋಧಕ ವರ್ಗ", "text": "ಇಸಿಇ ವಿಭಾಗದ ತಜ್ಞ ಸದಸ್ಯರು:\n\n1. ಪ್ರೊ. ಚೈತನ್ಯ ಕೆ. ಜಂಬೋಟ್ಕರ್ (ಎಚ್‌ಒಡಿ)\n2. ಡಾ. ವಿರೂಪಾಕ್ಷಿ ಬಿ. ದಲಾಲ್\n3. ಡಾ. ರಾಘವೇಂದ್ರ ಆರ್. ಮಗ್ಗವಿ\n4. ಡಾ. ವೀರೇಶ್ ಎಂ. ಹಿರೇಮಠ್\n5. ಡಾ. ಸೌಮ್ಯ ಹಲಗಟ್ಟಿ\n6. ಪ್ರೊ. ಗೋವಿಂದ ಎಂ ಆರ್\n7. ಪ್ರೊ. ವಿವೇಕ್ ಕಾಜಗರ\n8. ಪ್ರೊ. ನಾರಾಯಣ ರೆಡ್ಡಿ ಡಿ\n9. ಪ್ರೊ. ವಿಜಯಕುಮಾರ್ ಪಾಟೀಲ್\n10. ಪ್ರೊ. ಅಶ್ವಿನಿ ಎಲ್. ಗುಡಲಕರ್\n11. ಪ್ರೊ. ಸುಪ್ರಿಯಾ ಎನ್. ಕದ್ರೋಲ್ಕರ್\n12. ಪ್ರೊ. ರಜನಿ ವಿ ಆದಿಕರ್ನಾಟಕ\n13. ಪ್ರೊ. ಜಯಶ್ರೀ ಮೋರೆ\n14. ಪ್ರೊ. ಸ್ನೇಹಾ ಎ. ಜಗಜಂಪಿ", "imageUrl": "images/ece_dpt.jpg.jpeg" }
        },
        "5": {
            "en": { "title": "Artificial Intelligence & ML", "text": "The Department of Computer Science & Engineering (Artificial Intelligence and Machine Learning) was established in 2023 with an intake of 60. It is a dynamic and growing hub of innovation at JCER, Belagavi. Despite being new, our department has quickly established itself as a center for learning, offering a cutting-edge curriculum tailored to the ever-evolving fields of AI and ML. Our students are currently in their 7th semester, actively engaging with the latest technologies and hands-on projects.", "imageUrl": "images/AIML_dept.jpg.jpeg" },
            "hi": { "title": "आर्टिफिशियल इंटेलिजेंस और मशीन लर्निंग", "text": "कंप्यूटर विज्ञान और इंजीनियरिंग विभाग (आर्टिफिशियल इंटेलिजेंस और मशीन लर्निंग) 2023 में 60 की प्रवेश क्षमता के साथ स्थापित किया गया था। यह जेसीईआर, बेलगावी में नवाचार का एक गतिशील और बढ़ता हुआ केंद्र है। नया होने के बावजूद, हमारे विभाग ने खुद को सीखने के केंद्र के रूप में तेजी से स्थापित किया है, जो एआई और एमएल के निरंतर विकसित होने वाले क्षेत्रों के लिए तैयार किया गया एक अत्याधुनिक पाठ्यक्रम पेश करता है। हमारे छात्र वर्तमान में अपने 7वें सेमेस्टर में हैं, जो नवीनतम तकनीकों और व्यावहारिक परियोजनाओं के साथ सक्रिय रूप से जुड़े हुए हैं।", "imageUrl": "images/AIML_dept.jpg.jpeg" },
            "kn": { "title": "ಆರ್ಟಿಫಿಶಿಯಲ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಮತ್ತು ಮಷಿನ್ ಲರ್ನಿಂಗ್", "text": "ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಮತ್ತು ಇಂಜಿನಿಯರಿಂಗ್ ವಿಭಾಗವನ್ನು (ಆರ್ಟಿಫಿಶಿಯಲ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಮತ್ತು ಮಷಿನ್ ಲರ್ನಿಂಗ್) 2023 ರಲ್ಲಿ 60 ರ ಮೊತ್ತದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಯಿತು. ಇದು ಬೆಳಗಾವಿಯ JCER ನಲ್ಲಿ ನಾವೀನ್ಯತೆಯ ಕ್ರಿಯಾತ್ಮಕ ಮತ್ತು ಬೆಳೆಯುತ್ತಿರುವ ಕೇಂದ್ರವಾಗಿದೆ. ಹೊಸದಾಗಿದ್ದರೂ, ನಮ್ಮ ವಿಭಾಗವು ಕಲಿಕೆಯ ಕೇಂದ್ರವಾಗಿ ವೇಗವಾಗಿ ಸ್ಥಾಪಿತವಾಗಿದೆ, ಇದು AI ಮತ್ತು ML ನ ನಿರಂತರವಾಗಿ ವಿಕಸನಗೊಳ್ಳುತ್ತಿರುವ ಕ್ಷೇತ್ರಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಅತ್ಯಾಧುನಿಕ ಪಠ್ಯಕ್ರಮವನ್ನು ನೀಡುತ್ತದೆ. ನಮ್ಮ ವಿದ್ಯಾರ್ಥಿಗಳು ಪ್ರಸ್ತುತ ತಮ್ಮ 7 ನೇ ಸೆಮಿಸ್ಟರ್‌ನಲ್ಲಿದ್ದಾರೆ ಮತ್ತು ಇತ್ತೀಚಿನ ತಂತ್ರಜ್ಞಾನಗಳು ಮತ್ತು ಯೋಜನೆಗಳಲ್ಲಿ ತೊಡಗಿಸಿಕೊಂಡಿದ್ದಾರೆ.", "imageUrl": "images/AIML_dept.jpg.jpeg" }
        },
        "5_faculty": {
            "en": { "title": "AI & ML Faculty Members", "text": "The AI & ML department features a distinguished team of experts: \n\n1. Doctor Prakash K Sonwalkar (HOD)\n2. Doctor Anand Gudnavar\n3. Professor Swati Laxmeshwar\n4. Professor Sneha Khemalapure\n5. Professor Shashikala Reddy\n6. Professor Pallavi P. Dixit\n7. Professor Sakshi Joshi\n8. Professor Varsha Hiremath\n9. Professor Mamata Harogeri", "imageUrl": "images/AIML_dept.jpg.jpeg", "spokenText": "The faculty members are: Doctor Prakash K Sonwalkar, Doctor Anand Gudnavar, Professor Swati Laxmeshwar, Professor Sneha Khemalapure, Professor Shashikala Reddy, Professor Pallavi P. Dixit, Professor Sakshi Joshi, Professor Varsha Hiremath, and Professor Mamata Harogeri." },
            "hi": { "title": "एआई और एमएल संकाय", "text": "एआई और एमएल विभाग के सदस्य:\n\n1. डॉ. प्रकाश के सोनवलकर (एचओडी)\n2. डॉ. आनंद गुडनवर\n3. प्रो. स्वाति लक्ष्मेश्वर\n4. प्रो. स्नेहा खेमलापुरे\n5. प्रो. शशिकला रेड्डी\n6. प्रो. पल्लवी पी. दीक्षित\n7. प्रो. साक्षी जोशी\n8. प्रो. वर्षा हिरेमठ\n9. प्रो. ममता हरोगेरी", "imageUrl": "images/AIML_dept.jpg.jpeg" },
            "kn": { "title": "ಎಐ ಮತ್ತು ಎಂಎಲ್ ಬೋಧಕ ವರ್ಗ", "text": "ಎಐ ಮತ್ತು ಎಂಎಲ್ ವಿಭಾಗದ ಸದಸ್ಯರು:\n\n1. ಡಾ. ಪ್ರಕಾಶ್ ಕೆ ಸೋನವಾಲ್ಕರ್ (ಎಚ್‌ಒಡಿ)\n2. ಡಾ. ಆನಂದ್ ಗುಡ್ನವರ್\n3. ಪ್ರೊ. ಸ್ವಾತಿ ಲಕ್ಷ್ಮೆಶ್ವರ್\n4. ಪ್ರೊ. ಸ್ನೇಹ ಖೇಮಲಾಪುರೆ\n5. ಪ್ರೊ. ಶಶಿಕಲಾ ರೆಡ್ಡಿ\n6. ಪ್ರೊ. ಪಲ್ಲವಿ ಪಿ. ದೀಕ್ಷಿತ್\n7. ಪ್ರೊ. ಸಾಕ್ಷಿ ಜೋಷಿ\n8. ಪ್ರೊ. ವರ್ಷಾ ಹಿರೇಮಠ್\n9. ಪ್ರೊ. ಮಮತಾ ಹರೋಗೇರಿ", "imageUrl": "images/AIML_dept.jpg.jpeg" }
        },
        "6": {
            "en": { "title": "Mechanical Engineering", "text": "The Department of Mechanical Engineering was established in 2018 with an intake of 60, and a dedicated Research Center was added in 2024. To facilitate students, the department offers well-equipped laboratories and modern infrastructure. Our highly qualified faculty are dedicated to taking extra initiatives to mold students, preparing them to face the challenges of the competitive world.", "imageUrl": "images/mechanical_dpt.jpg.jpeg" },
            "hi": { "title": "मैकेनिकल इंजीनियरिंग", "text": "मैकेनिकल इंजीनियरिंग विभाग 2018 में 60 की प्रवेश क्षमता के साथ स्थापित किया गया था, और 2024 में एक समर्पित अनुसंधान केंद्र भी जोड़ा गया था। छात्रों की बेहतर शिक्षा के लिए, विभाग में उच्च तकनीक वाली प्रयोगशालाएं और आधुनिक बुनियादी ढांचा उपलब्ध है। हमारे अनुभवी और उच्च स्तरीय शिक्षक छात्रों को भविष्य की चुनौतियों के लिए तैयार करने और उनके सर्वांगीण विकास के लिए निरंतर प्रयास करते हैं।", "imageUrl": "images/mechanical_dpt.jpg.jpeg" },
            "kn": { "title": "ಮೆಕ್ಯಾನಿಕಲ್ ಇಂಜಿನಯರಿಂಗ್", "text": "ಮೆಕ್ಯಾನಿಕಲ್ ಇಂಜಿನಿಯರಿಂಗ್ ವಿಭಾಗವನ್ನು 2018 ರಲ್ಲಿ 60 ವಿದ್ಯಾರ್ಥಿಗಳ ಸಾಮರ್ಥ್ಯದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಯಿತು ಮತ್ತು 2024 ರಲ್ಲಿ ಸಂಶೋಧನಾ ಕೇಂದ್ರವನ್ನು ಪ್ರಾರಂಭಿಸಲಾಯಿತು. ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಉತ್ತಮ ಪ್ರಾಯೋಗಿಕ ಜ್ಞಾನ ನೀಡಲು ವಿಭಾಗವು ಅತ್ಯಾಧುನಿಕ ಪ್ರಯೋಗಾಲಯಗಳು ಮತ್ತು ಆಧುನಿಕ ಮೂಲಸೌಕರ್ಯಗಳನ್ನು ಹೊಂದಿದೆ. ನಮ್ಮ ಅನುಭವಿ ಬೋಧಕ ವರ್ಗವು ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಜಾಗತಿಕ ಸ್ಪರ್ಧೆ ಎದುರಿಸಲು ಸಿದ್ಧಪಡಿಸುವಲ್ಲಿ ಸದಾ ಶ್ರಮಿಸುತ್ತದೆ.", "imageUrl": "images/mechanical_dpt.jpg.jpeg" }
        },
        "6_faculty": {
            "en": { "title": "Mechanical Faculty Members", "text": "The Mechanical Engineering department features a distinguished team of experts: \n\n1. Doctor S.V. Gorabal (Principal)\n2. Doctor K. B. Jagadeeshgouda (HOD)\n3. Doctor Gangadhar M Kanaginahal\n4. Doctor Mallikarjun Jalageri\n5. Doctor Sadashiv Bellubbi\n6. Professor Karthik R\n7. Professor Rajshekar P Biradar\n8. Professor Praveen Patil\n9. Professor Prasanna Mangaonkar\n10. Professor Ganesh R. C\n11. Professor Santosh A\n12. Professor Sachin Kallannavar", "imageUrl": "images/mechanical_dpt.jpg.jpeg", "spokenText": "The faculty members are: Doctor S.V. Gorabal, Doctor K. B. Jagadeeshgouda, Doctor Gangadhar M Kanaginahal, Doctor Mallikarjun Jalageri, Doctor Sadashiv Bellubbi, Professor Karthik R, Professor Rajshekar P Biradar, Professor Praveen Patil, Professor Prasanna Mangaonkar, Professor Ganesh R. C, Professor Santosh A, and Professor Sachin Kallannavar." },
            "hi": { "title": "मैकेनिकल संकाय सदस्य", "text": "मैकेनिकल विभाग के सदस्य:\n\n1. डॉ. एस.वी. गोरबल (प्राचार्य)\n2. डॉ. के. बी. जगदीशगौड़ा (एचओडी)\n3. डॉ. गंगाधर एम कनागिनाहल\n4. डॉ. मल्लिकार्जुन जलगरी\n5. डॉ. सदाशिव बेलुब्बी\n6. प्रो. कार्तिक आर\n7. प्रो. राजशेखर पी बिरादर\n8. प्रो. प्रवीण पाटिल\n9. प्रो. प्रसन्न मनगांवकर\n10. प्रो. गणेश आर. सी\n11. प्रो. संतोष ए\n12. प्रो. सचिन कल्लन्नवर", "imageUrl": "images/mechanical_dpt.jpg.jpeg" },
            "kn": { "title": "ಮೆಕ್ಯಾನಿಕಲ್ ಬೋಧಕ ವರ್ಗ", "text": "ಮೆಕ್ಯಾನಿಕಲ್ ವಿಭಾಗದ ಸದಸ್ಯರು:\n\n1. ಡಾ. ಎಸ್.ವಿ. ಗೊರಬಾಳ್ (ಪ್ರಾಂಶುಪಾಲರು)\n2. ಡಾ. ಕೆ. ಬಿ. ಜಗದೀಶಗೌಡ (ಎಚ್‌ಒಡಿ)\n3. ಡಾ. ಗಂಗಾಧರ್ ಎಂ ಕಣಗಿನಹಾಳ\n4. ಡಾ. ಮಲ್ಲಿಕಾರ್ಜುನ್ ಜಲಗೇರಿ\n5. ಡಾ. ಸದಾಶಿವ ಬೆಳ್ಳುಬ್ಬಿ\n6. ಪ್ರೊ. ಕಾರ್ತಿಕ್ ಆರ್\n7. ಪ್ರೊ. ರಾಜಶೇಖರ್ ಪಿ ಬಿರಾದಾರ್\n8. ಪ್ರೊ. ಪ್ರವೀಣ್ ಪಾಟೀಲ್\n9. ಪ್ರೊ. ಪ್ರಸನ್ನ ಮನಗಾಂವಕರ್\n10. ಪ್ರೊ. ಗಣೇಶ್ ಆರ್. ಸಿ\n11. ಪ್ರೊ. ಸಂತೋಷ್ ಎ\n12. ಪ್ರೊ. ಸಚಿನ್ ಕಲ್ಲಣ್ಣವರ್", "imageUrl": "images/mechanical_dpt.jpg.jpeg" }
        },
        "7": {
            "en": { "title": "Civil Engineering", "text": "The Department of Civil Engineering was established in 2018 with an intake of 30. As a professional discipline, it deals with the design, construction, and maintenance of the physical and naturally built environment, including roads, bridges, canals, dams, and airports. Being the second-oldest engineering discipline, it plays a vital role in both the public and private sectors, serving everyone from individual homeowners to international companies.", "imageUrl": "images/civil_dept.jpg.jpeg" },
            "hi": { "title": "सिविल इंजीनियरिंग", "text": "सिविल इंजीनियरिंग विभाग 2018 में 30 की प्रवेश क्षमता के साथ स्थापित किया गया था। एक पेशेवर अनुशासन के रूप में, यह सड़कों, पुलों, नहरों, बांधों और हवाई अड्डों सहित भौतिक और प्राकृतिक रूप से निर्मित पर्यावरण के डिजाइन, निर्माण और रखरखाव से संबंधित है। दूसरी सबसे पुरानी इंजीनियरिंग विधा होने के नाते, यह सार्वजनिक और निजी दोनों क्षेत्रों में महत्वपूर्ण भूमिका निभाती है।", "imageUrl": "images/civil_dept.jpg.jpeg" },
            "kn": { "title": "ಸಿವಿಲ್ ಇಂಜಿನಿಯರಿಂಗ್", "text": "ಸಿವಿಲ್ ಇಂಜಿನಿಯರಿಂಗ್ ವಿಭಾಗವನ್ನು 2018 ರಲ್ಲಿ 30 ರ ಮೊತ್ತದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಯಿತು. ವೃತ್ತಿಪರ ಶಿಸ್ತಿನಂತೆ, ಇದು ರಸ್ತೆಗಳು, ಸೇತುವೆಗಳು, ಕಾಲುವೆಗಳು, ಅಣೆಕಟ್ಟುಗಳು ಮತ್ತು ವಿಮಾನ ನಿಲ್ದಾಣಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಭೌತಿಕ ಮತ್ತು ನೈಸರ್ಗಿಕವಾಗಿ ನಿರ್ಮಿಸಲಾದ ಪರಿಸರದ ವಿನ್ಯಾಸ, ನಿರ್ಮಾಣ ಮತ್ತು ನಿರ್ವಹಣೆಯನ್ನು ನಿರ್ವಹಿಸುತ್ತದೆ. ಇದು ಸಾರ್ವಜನಿಕ ಮತ್ತು ಖಾಸಗಿ ವಲಯಗಳಲ್ಲಿ ಪ್ರಮುಖ ಪಾತ್ರ ವಹಿಸುತ್ತದೆ.", "imageUrl": "images/civil_dept.jpg.jpeg" }
        },
        "7_faculty": {
            "en": { "title": "Civil Faculty Members", "text": "The Civil Engineering department features a distinguished team of experts: \n\n1. Professor Tungesh Naidu (HOD, Assistant Professor)\n2. Doctor Rajkumar V Raikar (Professor)\n3. Doctor R. Shreedhar (Professor)\n4. Professor Rahul R. Bannur (Assistant Professor)\n5. Professor Monika B (Assistant Professor)\n6. Professor Sheetal P N (Assistant Professor)\n7. Professor Soujanya V K (Assistant Professor)\n8. Professor Riya D. Kangralkar (Assistant Professor)\n9. Professor Ganesh Sayanekar (Assistant Professor)", "imageUrl": "images/civil_dept.jpg.jpeg", "spokenText": "The faculty members are: Professor Tungesh Naidu, Doctor Rajkumar V Raikar, Doctor R. Shreedhar, Professor Rahul R. Bannur, Professor Monika B, Professor Sheetal P N, Professor Soujanya V K, Professor Riya D. Kangralkar, and Professor Ganesh Sayanekar." },
            "hi": { "title": "सिविल संकाय सदस्य", "text": "सिविल विभाग के विशेषज्ञ सदस्य:\n\n1. प्रो. तुंगेश नायडू (एचओडी)\n2. डॉ. राजकुमार वी रायकर\n3. डॉ. आर. श्रीधर\n4. प्रो. राहुल आर. बन्नूर\n5. प्रो. मोनिका बी\n6. प्रो. शीतल पी एन\n7. प्रो. सौजन्या वी के\n8. प्रो. रिया डी. केंग्रलकर\n9. प्रो. गणेश सायनेकर", "imageUrl": "images/civil_dept.jpg.jpeg" },
            "kn": { "title": "ಸಿವಿಲ್ ಬೋಧಕ ವರ್ಗ", "text": "ಸಿವಿಲ್ ವಿಭಾಗದ ತಜ್ಞ ಸದಸ್ಯರು:\n\n1. ಪ್ರೊ. ತುಂಗೇಶ್ ನಾಯ್ಡು (ಎಚ್‌ಒಡಿ)\n2. ಡಾ. ರಾಜಕುಮಾರ್ ವಿ ರೈಕರ್\n3. ಡಾ. ಆರ್. ಶ್ರೀಧರ್\n4. ಪ್ರೊ. ರಾಹುಲ್ ಆರ್. ಬನ್ನೂರು\n5. ಪ್ರೊ. ಮೋನಿಕಾ ಬಿ\n6. ಪ್ರೊ. ಶೀತಲ್ ಪಿ ಎನ್\n7. ಪ್ರೊ. ಸೌಜನ್ಯ ವಿ ಕೆ\n8. ಪ್ರೊ. ರಿಯಾ ಡಿ. ಕಾಂಗ್ರಾಲ್ಕರ್\n9. ಪ್ರೊ. ಗಣೇಶ್ ಸಾಯನೇಕರ್", "imageUrl": "images/civil_dept.jpg.jpeg" }
        },
        "8": {
            "en": { "title": "Applied Science", "text": "The Basic Science Department is dedicated to laying a robust foundation in core principles of science, shaping the analytical and problem-solving skills of future engineers. Our team of highly qualified faculty is passionate about nurturing curiosity and academic excellence. Equipped with state-of-the-art laboratories and advanced teaching methodologies, we ensure an engaging learning experience. This solid grounding empowers students to excel throughout their engineering journey, setting the stage for innovative thinking and success in a technologically driven world.", "imageUrl": "images/Appscience_dept.jpg.jpeg" },
            "hi": { "title": "एप्लाइड साइंस", "text": "बेसिक साइंस विभाग इंजीनियरिंग की नींव रखने के लिए समर्पित है। हम भविष्य के इंजीनियरों के विश्लेषणात्मक कौशल को विकसित करने पर ध्यान केंद्रित करते हैं।", "imageUrl": "images/Appscience_dept.jpg.jpeg" },
            "kn": { "title": "ಅಪ್ಲೈಡ್ ಸೈನ್ಸ್", "text": "ಬೇಸಿಕ್ ಸೈನ್ಸ್ ವಿಭಾಗವು ಇಂಜಿನಿಯರಿಂಗ್‌ನ ಅಡಿಪಾಯ ಹಾಕಲು ಸಮರ್ಪಿತವಾಗಿದೆ. ಭವಿಷ್ಯದ ಇಂಜಿನಿಯರ್‌ಗಳ ವಿಶ್ಲೇಷಣಾತ್ಮಕ ಕೌಶಲ್ಯಗಳನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವತ್ತ ನಾವು ಗಮನ ಹರಿಸುತ್ತೇವೆ.", "imageUrl": "images/Appscience_dept.jpg.jpeg" }
        },
        "8_faculty": {
            "en": { "title": "Applied Science Faculty Members", "text": "The Applied Science department features a distinguished team of experts: \n\n1. Doctor Raghu Gunnagol (HOD)\n2. Professor Shweta Hiremath\n3. Professor Madhuri Bahadduri\n4. Professor Priyadarshini Udapudi\n5. Professor Shweta Patil\n6. Professor Aishwarya Dhamanekar\n7. Professor Tejashwini K Samay\n8. Professor G. S. Patil\n9. Professor Jasmith Charantimath\n10. Professor Vijaylaxmi Hulikatti\n11. Professor Sandhya Kambar\n12. Mister Anand T Salutigikar\n13. Professor Smita Shebannavar\n14. Professor Sheldon Telles\n15. Professor Shridhar S. Dharmatti", "imageUrl": "images/Appscience_dept.jpg.jpeg", "spokenText": "The faculty members are: Doctor Raghu Gunnagol, Professor Shweta Hiremath, Professor Madhuri Bahadduri, Professor Priyadarshini Udapudi, Professor Shweta Patil, Professor Aishwarya Dhamanekar, Professor Tejashwini K Samay, Professor G. S. Patil, Professor Jasmith Charantimath, Professor Vijaylaxmi Hulikatti, Professor Sandhya Kambar, Mister Anand T Salutigikar, Professor Smita Shebannavar, Professor Sheldon Telles, and Professor Shridhar S. Dharmatti." },
            "hi": { "title": "एप्लाइड साइंस संकाय", "text": "एप्लाइड साइंस विभाग सदस्य:\n\n1. डॉ. रघु गुणागोल (एचओडी)\n2. प्रो. श्वेता हिरेमठ\n3. प्रो. माधुरी बहादुरि\n4. प्रो. प्रियदर्शिनी उदापुडी\n5. प्रो. श्वेता पाटिल\n6. प्रो. ऐश्वर्या धमनेकर\n7. प्रो. तेजस्विनी के समय\n8. प्रो. जी. एस. पाटिल\n9. प्रो. जस्मिथ चरणतीमठ\n10. प्रो. विजयलक्ष्मी हुलीकट्टी\n11. प्रो. संध्या कंबार\n12. मिस्टर आनंद टी सालुटीगीकर\n13. प्रो. स्मिता शेबन्नवर\n14. प्रो. शेल्डन टेलेस\n15. प्रो. श्रीधर एस. धर्माट्टी", "imageUrl": "images/Appscience_dept.jpg.jpeg" },
            "kn": { "title": "ಅಪ್ಲೈಡ್ ಸೈನ್ಸ್ ಬೋಧಕ ವರ್ಗ", "text": "ಅಪ್ಲೈಡ್ ಸೈನ್ಸ್ ವಿಭಾಗದ ಸದಸ್ಯರು:\n\n1. ಡಾ. ರಘು ಗುಣಗೋಳ (ಎಚ್‌ಒಡಿ)\n2. ಪ್ರೊ. ಶ್ವೇತಾ ಹಿರೇಮಠ್\n3. ಪ್ರೊ. ಮಾಧುರಿ ಬಹದ್ದೂರಿ\n4. ಪ್ರೊ. ಪ್ರಿಯದರ್ಶಿನಿ ಉದಪುಡಿ\n5. ಪ್ರೊ. ಶ್ವೇತಾ ಪಾಟೀಲ್\n6. ಪ್ರೊ. ಐಶ್ವರ್ಯ ಧಮಣೇಕರ್\n7. ಪ್ರೊ. ತೇಜಸ್ವಿನಿ ಕೆ ಸಮಯ್\n8. ಪ್ರೊ. ಜಿ.ಎಸ್. ಪಾಟೀಲ್\n9. ಪ್ರೊ. ಜಸ್ಮಿತ್ ಚರಂತಿಮಠ್\n10. ಪ್ರೊ. ವಿಜಯಲಕ್ಷ್ಮಿ ಹುಲಿಕಟ್ಟಿ\n11. ಪ್ರೊ. ಸಂಧ್ಯಾ ಕಂಬಾರ್\n12. ಮಿಸ್ಟರ್ ಆನಂದ್ ಟಿ ಸಾಲುಟಿಗೀಕರ್\n13. ಪ್ರೊ. ಸ್ಮಿತಾ ಶೇಬಣ್ಣವರ್\n14. ಪ್ರೊ. ಶೆಲ್ಡನ್ ಟೆಲ್ಲೆಸ್\n15. ಪ್ರೊ. ಶ್ರೀಧರ್ ಎಸ್. ಧರ್ಮಟ್ಟಿ", "imageUrl": "images/Appscience_dept.jpg.jpeg" }
        },
        "9": {
            "en": { "title": "MBA Department", "text": "Established in 2024, our dynamic Department of MBA focuses on Digital Disruption, Analytics, and Modern Management practices. The department aims to develop visionary leaders equipped with contemporary management skills and an ethical mindset.", "imageUrl": "images/MBA_dept.jpg.jpeg" },
            "hi": { "title": "एमबीए विभाग", "text": "2024 में स्थापित हमारा एमबीए विभाग आधुनिक प्रबंधन प्रथाओं और डिजिटल नवाचार पर केंद्रित है।", "imageUrl": "images/MBA_dept.jpg.jpeg" },
            "kn": { "title": "ಎಂಬಿಎ ವಿಭಾಗ", "text": "2024 ರಲ್ಲಿ ಸ್ಥಾಪನೆಯಾದ ನಮ್ಮ ಎಂಬಿಎ ವಿಭಾಗವು ಆಧುನಿಕ ನಿರ್ವಹಣಾ ಪದ್ಧತಿಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ನಾವೀನ್ಯತೆಗಳ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ.", "imageUrl": "images/MBA_dept.jpg.jpeg" }
        },
        "9_faculty": {
            "en": { "title": "MBA Faculty Members", "text": "The MBA department features a distinguished team of experts: \n\n1. Doctor Indrajit Doddanavar\n2. Doctor Vrushali Pakhannavar\n3. Mister Sangam B. Jadhav\n4. CA. Vinayak Asundi\n5. Professor Sandhya Sherigar\n6. Mister Pavankumar Ramgouda", "imageUrl": "images/MBA_dept.jpg.jpeg", "spokenText": "The faculty members are: Doctor Indrajit Doddanavar, Doctor Vrushali Pakhannavar, Mister Sangam B. Jadhav, CA Vinayak Asundi, Professor Sandhya Sherigar, and Mister Pavankumar Ramgouda." },
            "hi": { "title": "एमबीए संकाय सदस्य", "text": "एमबीए विभाग सदस्य:\n\n1. डॉ. इंद्रजीत दोड्डनवर\n2. डॉ. वृषाली पखनवर\n3. मिस्टर संगम जाधव\n4. सीए विनायक असुंडी\n5. प्रो. संध्या शेरिगर\n6. मिस्टर पवनकुमार रामगौड़ा", "imageUrl": "images/MBA_dept.jpg.jpeg" },
            "kn": { "title": "ಎಂಬಿಎ ಬೋಧಕ ವರ್ಗ", "text": "ಎಂಬಿಎ ವಿಭಾಗದ ಸದಸ್ಯರು:\n\n1. ಡಾ. ಇಂದ್ರಜಿತ್ ದೊಡ್ಡನವರ್\n2. ಡಾ. ವೃಶಾಲಿ ಪಖನ್ನವರ್\n3. ಮಿಸ್ಟರ್ ಸಂಗಮ್ ಬಿ ಜಾದವ್\n4. ಸಿಎ ವಿನಾಯಕ್ ಅಸುಂಡಿ\n5. ಪ್ರೊ. ಸಂಧ್ಯಾ ಶೇರಿಗಾರ್\n6. ಮಿಸ್ಟರ್ ಪವನಕುಮಾರ್ ರಾಮಗೌಡ", "imageUrl": "images/MBA_dept.jpg.jpeg" }
        },
        "10": {
            "en": { "title": "College Rules", "text": "Character building is our main aim. Discipline, attendance, and ethics are strictly enforced at JCER.", "imageUrl": null },
            "hi": { "title": "कॉलेज के नियम", "text": "अनुशासन, उपस्थिति और नैतिकता जेसीईआर में दृढ़ता से लागू की जाती है। छात्र का सर्वांगीण विकास हमारा मुख्य लक्ष्य है।", "imageUrl": null },
            "kn": { "title": "ಕಾಲೇಜು ನಿಯಮಗಳು", "text": "ಶಿಸ್ತು, ಹಾಜರಾತಿ ಮತ್ತು ನೈತಿಕತೆಯನ್ನು ಜೆಸಿಇಆರ್ ನಲ್ಲಿ ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ. ವಿದ್ಯಾರ್ಥಿಯ ಸರ್ವತೋಮುಖ ಅಭಿವೃದ್ಧಿ ನಮ್ಮ ಮುಖ್ಯ ಗುರಿಯಾಗಿದೆ.", "imageUrl": null }
        },
        "11": {
            "en": { "title": "Canteen", "text": "Our college canteen is very clean and well maintained. The surroundings are neat, and proper hygiene is followed while preparing food. Clean water is available, and the seating area is comfortable for students to sit and relax.\n\nThe food in our canteen is very tasty and fresh. Different types of snacks, meals, and drinks are available.", "imageUrl": null },
            "hi": { "title": "कैंटीन", "text": "हमारा कॉलेज कैंटीन बहुत साफ और स्वच्छ है। हम छात्रों के लिए ताजा और स्वादिष्ट भोजन और बैठने के लिए आरामदायक जगह प्रदान करते हैं।", "imageUrl": null },
            "kn": { "title": "ಕ್ಯಾಂಟೀನ್", "text": "ನಮ್ಮ ಕಾಲೇಜು ಕ್ಯಾಂಟೀನ್ ತುಂಬಾ ಸ್ವಚ್ಛ ಮತ್ತು ನೈರ್ಮಲ್ಯದಿಂದ ಕೂಡಿದೆ. ನಾವು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ತಾಜಾ ಮತ್ತು ರುಚಿಕರವಾದ ಆಹಾರ ಮತ್ತು ಕುಳಿತುಕೊಳ್ಳಲು ಆರಾಮದಾಯಕವಾದ ಸ್ಥಳವನ್ನು ಒದಗಿಸುತ್ತೇವೆ.", "imageUrl": null }
        },
        "12": {
            "en": { "title": "Campus Facilities", "text": "JCER offers world-class infrastructure to support your academic journey: \n\n• Well-equipped Laboratories in each department\n• Modern Computer Centre with latest machines and software\n• Transportation with 7+ buses\n• Centralized Computing facility with 200+ computers on network\n• 300 Mbps Internet connectivity, Wi-fi, CCTV surveillance\n• Ultra-modern Library (10,000+ volumes, E-Library)\n• Training & Placement Cell\n• Outdoor & Indoor Sports facilities\n• Digital Classrooms with video conferencing\n• IT Incubation Centre\n• Well maintained canteens and mess\n• Provisions for easy access (Ramps & Lifts)", "imageUrl": "images/Facility.jpg.jpeg", "spokenText": "JCER provides world-class infrastructure including well-equipped laboratories, modern computer centers, transportation, high-speed internet, an ultra-modern library, digital classrooms, and excellent sports facilities." },
            "hi": { "title": "कैंपस सुविधाएं", "text": "जेसीईआर विश्व स्तरीय बुनियादी ढांचा प्रदान करता है, जिसमें आधुनिक प्रयोगशालाएं, उच्च गति इंटरनेट, एक विशाल पुस्तकालय और खेल सुविधाएं शामिल हैं।", "imageUrl": "images/Facility.jpg.jpeg" },
            "kn": { "title": "ಕ್ಯಾಂಪಸ್ ಸೌಲಭ್ಯಗಳು", "text": "ಜೆಸಿಇಆರ್ ಆಧುನಿಕ ಪ್ರಯೋಗಾಲಯಗಳು, ಹೈ-ಸ್ಪೀಡ್ ಇಂಟರ್ನೆಟ್, ಬೃಹತ್ ಗ್ರಂಥಾಲಯ ಮತ್ತು ಕ್ರೀಡಾ ಸೌಲಭ್ಯಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ವಿಶ್ವದರ್ಜೆಯ ಮೂಲಸೌಕರ್ಯಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.", "imageUrl": "images/Facility.jpg.jpeg" }
        },
        "13": {
            "en": { "title": "Placements", "text": "JCER offers a dedicated Placement Cell that provides robust training and placement opportunities for all our students. We have consistently achieved excellent placement records with top multinational companies. Based on 2025 placement reports, the Jain Deemed-to-be University (Faculty of Engineering and Technology) in Bangalore offers an average package of around 8 Lakhs per year for its BTech programs, with top performers achieving significantly higher. Computer Science and Engineering (CSE) students generally secure high packages, often within the top salary brackets.\n\nKey Placement Highlights (2025/Recent):\n• Average Package: Approx. 8 Lakhs per year.\n• Highest Package: Reached up to 81.25 Lakhs per year in 2025.\n• Top Recruiters: Companies like Samsung, Silicon Labs, TCS, and Siemens visited the campus.\n• Placement Data: Over 3,000 companies participated in the 2025 campus recruitment, with over 2,500 offers made.", "imageUrl": null, "spokenText": "JCER offers a dedicated Placement Cell that provides robust training and placement opportunities for all our students. We have consistently achieved excellent placement records with top multinational companies. Based on 2025 placement reports, the Jain Deemed-to-be University (Faculty of Engineering and Technology) in Bangalore offers an average package of around 8 Lakhs per year for its BTech programs, with top performers achieving significantly higher. Computer Science and Engineering (CSE) students generally secure high packages, often within the top salary brackets. Key Placement Highlights (2025/Recent): Average Package: Approx. 8 Lakhs per year. Highest Package: Reached up to 81.25 Lakhs per year in 2025. Top Recruiters: Companies like Samsung, Silicon Labs, TCS, and Siemens visited the campus. Placement Data: Over 3,000 companies participated in the 2025 campus recruitment, with over 2,500 offers made." },
            "hi": { "title": "प्लेसमेंट", "text": "जेसीईआर एक समर्पित प्लेसमेंट सेल प्रदान करता है जो हमारे सभी छात्रों के लिए मजबूत प्रशिक्षण और प्लेसमेंट के अवसर प्रदान करता है। हमने शीर्ष बहुराष्ट्रीय कंपनियों के साथ लगातार उत्कृष्ट प्लेसमेंट रिकॉर्ड हासिल किए हैं। 2025 की प्लेसमेंट रिपोर्ट के आधार पर, बैंगलोर में जैन डीम्ड-टू-बी यूनिवर्सिटी (फैकल्टी ऑफ इंजीनियरिंग एंड टेक्नोलॉजी) अपने बीटेक कार्यक्रमों के लिए लगभग 8 लाख प्रति वर्ष का औसत पैकेज प्रदान करती है, जिसमें शीर्ष प्रदर्शन करने वाले छात्र काफी अधिक पैकेज प्राप्त करते हैं। कंप्यूटर विज्ञान और इंजीनियरिंग (सीएसई) के छात्र आमतौर पर उच्च पैकेज सुरक्षित करते हैं।\n\nप्रमुख प्लेसमेंट मुख्य अंश (2025/नवीनतम):\n• औसत पैकेज: लगभग 8 लाख प्रति वर्ष।\n• उच्चतम पैकेज: 2025 में 81.25 लाख प्रति वर्ष तक पहुंचा।\n• शीर्ष रिक्रूटर्स: सैमसंग, सिलिकॉन लैब्स, टीसीएस और सीमेंस जैसी कंपनियों ने कैंपस का दौरा किया।\n• प्लेसमेंट डेटा: 2025 कैंपस भर्ती में 3,000 से अधिक कंपनियों ने भाग लिया, जिसमें 2,500 से अधिक प्रस्ताव दिए गए।", "imageUrl": null },
            "kn": { "title": "ಪ್ಲೇಸ್‌ಮೆಂಟ್ಸ್", "text": "ನಮ್ಮ ಎಲ್ಲಾ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಉತ್ತಮ ತರಬೇತಿ ಮತ್ತು ಉದ್ಯೋಗಾವಕಾಶಗಳನ್ನು ಒದಗಿಸುವ ಮೀಸಲಾದ ಪ್ಲೇಸ್‌ಮೆಂಟ್ ಸೆಲ್ ಅನ್ನು ಜೆಸಿಇಆರ್ ಹೊಂದಿದೆ. ನಾವು ಉನ್ನತ ಬಹುರಾಷ್ಟ್ರೀಯ ಕಂಪನಿಗಳೊಂದಿಗೆ ಅತ್ಯುತ್ತಮ ಉದ್ಯೋಗ ದಾಖಲೆಗಳನ್ನು ಸಾಧಿಸಿದ್ದೇವೆ. 2025 ರ ಪ್ಲೇಸ್‌ಮೆಂಟ್ ವರದಿಗಳ ಆಧಾರದ ಮೇಲೆ, ಬೆಂಗಳೂರಿನ ಜೈನ್ ಡೀಮ್ಡ್-ಟು-ಬಿ ವಿಶ್ವವಿದ್ಯಾಲಯ (ಎಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ವಿಭಾಗ) ತನ್ನ ಬಿಟೆಕ್ ಕಾರ್ಯಕ್ರಮಗಳಿಗೆ ಸರಿಸುಮಾರು 8 ಲಕ್ಷ ಪ್ರತಿ ವರ್ಷ ಸರಾಸರಿ ಪ್ಯಾಕೇಜ್ ನೀಡುತ್ತದೆ, ಉನ್ನತ ಸಾಧಕರು ಗಣನೀಯವಾಗಿ ಹೆಚ್ಚಿನ ಪ್ಯಾಕೇಜ್ ಪಡೆಯುತ್ತಾರೆ. ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ ಮತ್ತು ಎಂಜಿನಿಯರಿಂಗ್ (ಸಿಎಸ್‌ಇ) ವಿದ್ಯಾರ್ಥಿಗಳು ಸಾಮಾನ್ಯವಾಗಿ ಹೆಚ್ಚಿನ ಪ್ಯಾಕೇಜ್‌ಗಳನ್ನು ಪಡೆಯುತ್ತಾರೆ.\n\nಪ್ರಮುಖ ಪ್ಲೇಸ್‌ಮೆಂಟ್ ಮುಖ್ಯಾಂಶಗಳು (2025/ಇತ್ತೀಚಿನ):\n• ಸರಾಸರಿ ಪ್ಯಾಕೇಜ್: ಅಂದಾಜು 8 ಲಕ್ಷ ಪ್ರತಿ ವರ್ಷ.\n• ಅತಿ ಹೆಚ್ಚು ಪ್ಯಾಕೇಜ್: 2025 ರಲ್ಲಿ 81.25 ಲಕ್ಷ ಪ್ರತಿ ವರ್ಷ ತಲುಪಿದೆ.\n• ಉನ್ನತ ನೇಮಕಾತಿದಾರರು: ಸ್ಯಾಮ್ಸಂಗ್, ಸಿಲಿಕಾನ್ ಲ್ಯಾಬ್ಸ್, ಟಿಸಿಎಸ್, ಮತ್ತು ಸೀಮೆನ್ಸ್ ನಂತಹ ಕಂಪನಿಗಳು ಕ್ಯಾಂಪಸ್‌ಗೆ ಭೇಟಿ ನೀಡಿದ್ದವು.\n• ಪ್ಲೇಸ್‌ಮೆಂಟ್ ಡೇಟಾ: 2025 ರ ಕ್ಯಾಂಪಸ್ ನೇಮಕಾತಿಯಲ್ಲಿ 3,000 ಕ್ಕೂ ಹೆಚ್ಚು ಕಂಪನಿಗಳು ಭಾಗವಹಿಸಿದ್ದು, 2,500 ಕ್ಕೂ ಹೆಚ್ಚು ಆಫರ್‌ಗಳನ್ನು ನೀಡಲಾಗಿದೆ.", "imageUrl": null }

        },
        "#": {
            "en": { "title": "Contact Us", "text": "Contact us via email at principal@jcer.in or call us at 09448693987.", "imageUrl": "images/contact.jpg.jpeg" },
            "hi": { "title": "संपर्क करें", "text": "आप हमें principal@jcer.in पर ईमेल कर सकते हैं या 09448693987 पर कॉल कर सकते हैं।", "imageUrl": "images/contact.jpg.jpeg" },
            "kn": { "title": "ಸಂಪರ್ಕಿಸಿ", "text": "ನೀವು ನಮಗೆ principal@jcer.in ನಲ್ಲಿ ಇಮೇಲ್ ಮಾಡಬಹುದು ಅಥವಾ 09448693987 ಗೆ ಕರೆ ಮಾಡಬಹುದು.", "imageUrl": "images/contact.jpg.jpeg" }
        }
    };

    const topicData = db[topic];
    if (topicData) {
        const info = topicData[lang] || topicData['en'];
        res.status(200).json(info);
    } else {
        res.status(404).json({ error: "Topic not found" });
    }
}
